import type { Metadata } from "next";
import "./globals.css";
import { AuthContextProvider } from "@/providers/auth.provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <AuthContextProvider>{children}</AuthContextProvider>
      </body>
    </html>
  );
}
