apiVersion: v1
kind: Secret
metadata:
  namespace: social-networks
  name: deamon
type: Opaque
stringData:
  # MySQL Configs
  MYSQL_USER: "deamon_app"
  MYSQL_PASS: "supersecret"
  MYSQL_HOST: "mysql-write"
  MYSQL_MAX_POOL_SIZE: "20"
  MYSQL_QUEUE_LIMIT: "0"
  MYSQL_PORT: "3306"

  # gRPC Configs
  GRPC_USER_PORT: "50051"
  HEALTH_PORT: "3000"
  # SMTP Configs
  SMTP_HOST: "smtp.ethereal.email"
  SMTP_PORT: "1025"
  SMTP_SECURE: "tls"
  MAIL_USER: "deadletter@localhost.co"
  MAIL_PASS: "1f5yWKNNvraVT6Zmrr"
  ALERT_RECIPIENT: "lucas.lowe@ethereal.email"