apiVersion: v1
kind: Service

metadata:
  name: mysql-operator
  namespace: social-networks

  labels:
    app: mysql
    role: service

spec:
  selector:
    app: mysql
    role: mysql-operator

  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
