apiVersion: skaffold/v4beta14
kind: Config

metadata:
  name: mysql

build:
  local:
    push: false
  artifacts:
    - image: busybox-test
      context: .
      docker:
        dockerfile: busybox/Dockerfile
        target: busybox

manifests:
  rawYaml:
#     - k8s/account/*.yaml
#     - k8s/service/*.yaml
      - busybox/k8s/*.yaml

deploy:
  kubectl:
    flags:
      apply:
        - --force # Forces recreation of immutable objects like Jobs
portForward:
  - resourceType: Deployment
    resourceName: busybox
    port: 3000
    localPort: 3000