name: Build and Push to ECR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::720215340864:role/github-to-aws-oict
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 \
            | docker login --username AWS --password-stdin 720215340864.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: docker build -f app/user/Dockerfile -t user-service .

      - name: Tag Docker image
        run: docker tag user-service:latest 720215340864.dkr.ecr.us-east-1.amazonaws.com/my-ci-cd-pipeline:latest

      - name: Push Docker image
        run: docker push 720215340864.dkr.ecr.us-east-1.amazonaws.com/my-ci-cd-pipeline:latest
