name: Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASS }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DB }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASS }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -p${{ secrets.MYSQL_PASS }}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h127.0.0.1 -uroot -p${{ secrets.MYSQL_PASS }} --silent; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Run Flyway migrations
        uses: flyway/flyway-action@v2
        with:
          url: jdbc:mysql://127.0.0.1:3306/${{ secrets.MYSQL_DB }}
          user: ${{ secrets.MYSQL_USER }}
          password: ${{ secrets.MYSQL_PASS }}
          locations: filesystem:./migrations

      - name: Run tests
        env:
          ENV: test
          ENVIRONMENT: testing
          JWT_VERIFICATION_REQUEST_SECRET_KEY: ${{ secrets.JWT_VERIFICATION_REQUEST_SECRET_KEY }}
          JWT_VERIFICATION_REQUEST_TTL: ${{ secrets.JWT_VERIFICATION_REQUEST_TTL }}

          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASS: ${{ secrets.MONGO_PASS }}
          MONGO_PORT: ${{ secrets.MONGO_PORT }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          MONGO_MAX_POOL_SIZE: ${{ secrets.MONGO_MAX_POOL_SIZE }}

          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASS: ${{ secrets.MYSQL_PASS }}
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
          MYSQL_DB: ${{ secrets.MYSQL_DB }}
          MYSQL_MAX_POOL_SIZE: ${{ secrets.MYSQL_MAX_POOL_SIZE }}
          MYSQL_QUEUE_LIMIT: ${{ secrets.MYSQL_QUEUE_LIMIT }}

          GRPC_USER_PORT: ${{ secrets.GRPC_USER_PORT }}
        run: npm test
