name: Set up services and run tests

on:
  push:
    branches: ["main", "test-ci"]
  pull_request:
    branches: ["main", "test-ci"]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ENV: test
      ENVIRONMENT: testing

      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3306
      MYSQL_DB: testdb
      MYSQL_USER: root
      MYSQL_PASS: root

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h127.0.0.1 -uroot -proot --silent; do
            echo "Waiting for MySQL..."
            sleep 5
          done
      # Start RabbitMQ and install delayed plugin
      - name: Start RabbitMQ with delayed plugin
        run: |
          docker rm -f rabbitmq || true
          docker run -d --name rabbitmq \
            -p 5672:5672 -p 15672:15672 \
            rabbitmq:3.13-management

          # Install plugin
          docker exec rabbitmq bash -c "apt-get update && apt-get install -y wget && \
            wget -O /plugins/rabbitmq_delayed_message_exchange-3.13.0.ez \
            https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.13.0/rabbitmq_delayed_message_exchange-3.13.0.ez"

          # Enable plugin
          docker exec rabbitmq rabbitmq-plugins enable rabbitmq_delayed_message_exchange

          # Restart to load plugin
          docker restart rabbitmq

      - name: Wait for RabbitMQ
        run: |
          until nc -z 127.0.0.1 5672; do
            echo "Waiting for RabbitMQ..."
            sleep 5
          done
      - name: Run Flyway migrations (Docker)
        run: |
          docker run --rm \
            --network host \
            -v ${{ github.workspace }}/migrations/flyway/migrations:/flyway/sql \
            flyway/flyway:latest \
            -url="jdbc:mysql://127.0.0.1:3306/testdb" \
            -user="root" \
            -password="root" \
            migrate

      - name: Verify DB
        run: |
          mysql -h127.0.0.1 -uroot -proot -e "SHOW TABLES;" testdb

      - name: Run tests
        run: npm test
