name: Set up services and run tests

on:
  push:
    branches: ["main", "test-ci"]
  pull_request:
    branches: ["main", "test-ci"]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ENV: test
      ENVIRONMENT: testing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Make setup script executable
        run: chmod +x test.containers.setup.sh

      - name: Set up test services
        run: ./test.containers.setup.sh

      - name: Wait for MySQL
        run: |
          until docker compose -f tests/docker-compose.yaml exec -T mysql mysqladmin ping -h localhost --silent; do
            echo "Waiting for MySQL to accept connections..."
            sleep 3
          done

      - name: Wait for RabbitMQ
        run: |
          until docker compose -f tests/docker-compose.yaml exec -T rabbitmq rabbitmq-diagnostics -q ping; do
            echo "Waiting for RabbitMQ..."
            sleep 3
          done

      - name: Wait for Flyway Migrations
        run: |
          until docker compose -f tests/docker-compose.yaml exec -T mysql mysql -uroot -p"supersecret" -e "SHOW TABLES;" test_db | grep -q "user_credentials"; do
            echo "Waiting for Flyway migrations to complete..."
            sleep 3
          done

      - name: Run tests
        run: npm run test

      - name: Tear down test services
        if: always()
        run: docker compose -f tests/docker-compose.yaml down -v