name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ENV: test
      ENVIRONMENT: testing

      JWT_VERIFICATION_REQUEST_SECRET_KEY: test_secerte
      JWT_VERIFICATION_REQUEST_TTL: 2m

      MONGO_USER: admin
      MONGO_PASS: secret
      MONGO_PORT: 27017
      MONGO_DB: test_db
      MONGO_MAX_POOL_SIZE: 20

      MYSQL_USER: root
      MYSQL_PASS: supersecret
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3306
      MYSQL_DB: test_db
      MYSQL_MAX_POOL_SIZE: 20
      MYSQL_QUEUE_LIMIT: 0

      GRPC_USER_PORT: 50051

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: supersecret
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -psupersecret"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h127.0.0.1 -uroot -psupersecret --silent; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Run Flyway migrations (Docker)
        run: |
          docker run --rm \
            --network host \
            -v ${{ github.workspace }}/migrations/flyway/migrations:/flyway/sql \
            flyway/flyway:latest \
            -url="jdbc:mysql://127.0.0.1:3306/test_db" \
            -user="root" \
            -password="supersecret" \
            migrate

      - name: Verify DB connection
        run: |
          mysql -h127.0.0.1 -uroot -psupersecret -e "SHOW TABLES;" test_db

      - name: Run tests
        run: npm test